version: '3.8'

services:
  fullstack-nest-backend:
    image: lgdweb/fullstack-nest-backend:prod
    container_name: fullstack-nest-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SESSION_TTL: ${SESSION_TTL}
      RUN_MIGRATIONS: 'true'
    volumes:
      - data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped

  fullstack-astro-frontend:
    image: lgdweb/fullstack-astro-frontend:prod
    container_name: fullstack-astro-frontend
    environment:
      API_URL: ${API_URL}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    ports:
      - 4321:4321
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped
    depends_on:
      - fullstack-nest-backend

volumes:
  data:

networks:
  default-nw:
    external: true
  reverse-proxy-nw:
    external: true
